jenkins.hideButtons="no"
jenkins.hideTriggerButton="no"
jenkins.hideDashBoardButton="no"
jenkins.processurl=""
jenkins.wsprocessname="Deploy"
jenkins.wsprocessurl="http://localhost:8080/testjenkins/test/jsshconnect"
jenkins.autosubmit="yes"
jenkins.showhistory="yes"
jenkins.sendtoJira='yes'
jenkins.jiraServer='http://localhost:8181/'
jenkins.jiraUser='jira'
jenkins.jiraPass='jira'
jenkins.jira.AccessUri="/browse/"
jenkins.jiraSendType='comment'
//jenkins.customField='10010' // the id of your customfield
// Auto submit wsprocess url ?
jenkins.autosubmit = "yes"
jenkins.showsummary = "yes"
jenkins.jira.AccessUri = "/browse/"
jenkins.jiraSendType = 'customfield'
jenkins.customField = '12330' // the id of your customfield
jenkins.sendApi = true  // true/false - by default false
jenkins.sendChangeSet = true  // true/false - by default false
jenkins.sendBuildId = true  // true/false - by default false
jenkins.sendBuildUser = true  // true/false - by default false
jenkins.sendChanges = true  // true/false - by default false
jenkins.sendParseConsole = true  // true/false - by default false
jenkins.parseBuildingWorkSpace = true  // true/false - by default false
jenkins.parseBuilding = true  // true/false - by default false
jenkins.parseDoneCreating = true  // true/false - by default false
jenkins.parseLastTrans = true  // true/false - by default false
jenkins.summaryViewButtons = "yes"
jenkins.summaryFileButton = "yes"
jenkins.summaryChangesButton = "yes"
jenkins.jiraButtons = "yes"
jenkins.jiraOverwriteButton = "yes"
jenkins.jiraAppendButton = "yes"
jenkins.jiraCommentButton = "yes"

jssh.USER = "mx1"
jssh.PASS = ""
jssh.KEY="/home/mx1/.ssh/id_rsa"
jssh.timeout="0"
jssh.disable.login="NO"
jssh.NEWCONNPERTRANS='NO'
jssh.hideSessionCtrl="NO"
jssh.hideAuthBlock='NO'
jssh.hideConsoleMenu="NO"
jssh.hideSendBlock="NO"
jssh.hidePauseControl="NO"
jssh.hideWhatsRunning="NO"
jssh.hideDiscoButton="NO"
jssh.hideNewShellButton="NO"

